### ISSUE TITLE
USB EHCI Debug possible?

### ISSUE THREAD

**Issue by segfault-bilibili** [Theldus/bread#4]
https://www.coreboot.org/EHCI_Debug_Port

https://www.reddit.com/r/libreboot/s/Fe2Lge9voe

**Comment by Theldus** [comment]
Hi @segfault-bilibili,
This project is meant to be used at legacy/pre-UEFI BIOSes, and hardware from this era easily has serial ports available, in fact, even recent motherboards still have a serial header on them.

That said, I don't believe it's worth all the effort to support USB, when a serial<->USB (like [this one](https://pisces.bbystatic.com/image2/BestBuy_US/images/products/5883/5883029_sd.jpg)) cable is all you need to use it.

**Comment by segfault-bilibili** [comment]
Thanks. I'm just asking whether it's technically possible. Laptops may not have serial port therefore I'm thinking about this.
